### ISSUE TITLE
Hyperlinks for ArNS testnet names resolve to mainnet gateway

### ISSUE THREAD

**Issue by kempsterrrr** [ar-io/arns-react#845]
When using ArNS app in testing mode, the hyperlinks in the manage assets dashboard link to `ar.io` rather than the testnet gateway `ar-io.dev`

See the example below, the url this links to should be `specialkevmtest.ar-io.dev`

This causes confusion for me when I am testing deployments as the resolved URL does not show what it should show

FWIW I am on chrome and connected with an EVM wallet via MM

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/dcbc12e7-6b2c-4d81-8418-6c8dd8c68af3" />

**Comment by dtfiedler** [comment]
Thanks @kempsterrrr - we'll update later today.

**Comment by dtfiedler** [comment]
Hey @kempsterrrr - we pushed this fix with v1.23.0

**Comment by kempsterrrr** [comment]
Think I'm still seeing this, hard-refreshed on arns.app and I'm getting the mainnet gateway.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/aabeb913-1880-4779-8714-f91e4bdba6a2" />
